// ============ Core Types ============

export interface User {
  id: string;
  email: string;
  name: string;
  image?: string;
  isAdmin: boolean;
  role?: 'admin' | 'superuser' | 'user';
}

// ============ Category Types ============

export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string;
  createdBy: string;
  createdAt: Date;
}

export interface CategoryWithStats extends Category {
  documentCount: number;
  superUserCount: number;
  subscriberCount: number;
}

export interface UserSubscription {
  categoryId: number;
  categoryName: string;
  categorySlug: string;
  isActive: boolean;
}

export interface SuperUserAssignment {
  categoryId: number;
  categoryName: string;
  categorySlug: string;
}

// ============ Thread Types ============

export interface Thread {
  id: string;
  userId: string;
  title: string;
  createdAt: Date;
  updatedAt: Date;
  uploadCount: number;
  categories?: ThreadCategory[];
  isSummarized?: boolean;
  totalTokens?: number;
}

export interface ThreadCategory {
  id: number;
  name: string;
  slug: string;
}

export interface ThreadWithMessages extends Thread {
  messages: Message[];
  uploads: string[];
  categories?: ThreadCategory[];
}

// ============ Message Types ============

// Tool call types for OpenAI function calling
export interface ToolCall {
  id: string;
  type: 'function';
  function: {
    name: string;
    arguments: string; // JSON string
  };
}

export interface Message {
  id: string;
  role: 'user' | 'assistant' | 'tool';
  content: string;
  tool_calls?: ToolCall[];      // For assistant messages with tool calls
  tool_call_id?: string;        // For tool response messages
  name?: string;                // Tool name for tool responses
  sources?: Source[];
  attachments?: string[];
  generatedDocuments?: GeneratedDocumentInfo[]; // Documents generated by autonomous doc_gen tool
  visualizations?: MessageVisualization[]; // Visualizations from data_source tool
  timestamp: Date;
}

// Generated document info returned by doc_gen tool
export interface GeneratedDocumentInfo {
  id: string;
  filename: string;
  fileType: 'pdf' | 'docx' | 'md';
  fileSize: number;
  fileSizeFormatted: string;
  downloadUrl: string;
  expiresAt: string | null;
}

// Visualization data extracted from data_source or chart_gen tool
export interface MessageVisualization {
  chartType: 'bar' | 'line' | 'pie' | 'area' | 'scatter' | 'radar' | 'table';
  data: Record<string, unknown>[];
  xField?: string;
  yField?: string;
  groupBy?: string;
  sourceName?: string;
  cached?: boolean;
  fields?: string[];
  title?: string;
  /** Notes about data sources/methodology (from chart_gen) */
  notes?: string;
  /** Series display mode for multi-series charts (from chart_gen) */
  seriesMode?: 'grouped' | 'stacked' | 'auto';
}

export interface Source {
  documentName: string;
  pageNumber: number;
  chunkText: string;
  score: number;
}

// ============ Document Types ============

export interface DocumentCategory {
  id: number;
  name: string;
  slug: string;
}

export interface GlobalDocument {
  id: string;
  filename: string;
  filepath: string;
  size: number;
  chunkCount: number;
  uploadedAt: Date;
  uploadedBy: string;
  status: 'processing' | 'ready' | 'error';
  errorMessage?: string;
  isGlobal?: boolean;
  categories?: DocumentCategory[];
}

export interface DocumentChunk {
  id: string;
  text: string;
  metadata: ChunkMetadata;
  embedding?: number[];
}

export interface ChunkMetadata {
  documentId: string;
  documentName: string;
  pageNumber: number;
  chunkIndex: number;
  source: 'global' | 'user';
  threadId?: string;
  userId?: string;
}

// ============ API Request Types ============

export interface ChatRequest {
  message: string;
  threadId: string;
}

export interface TranscribeRequest {
  audio: File;
}

export interface CreateThreadRequest {
  title?: string;
  categoryIds?: number[];
}

export interface UpdateThreadRequest {
  title?: string;
  categoryIds?: number[];
}

// ============ API Response Types ============

export interface ChatResponse {
  message: Message;
  threadId: string;
}

export interface TranscribeResponse {
  text: string;
  duration: number;
}

export interface ThreadListResponse {
  threads: Thread[];
  total: number;
}

export type ThreadResponse = ThreadWithMessages;

export interface DeleteThreadResponse {
  success: boolean;
  deleted: {
    threadId: string;
    messageCount: number;
    uploadCount: number;
  };
}

export interface UploadResponse {
  filename: string;
  size: number;
  uploadCount: number;
}

export interface AdminDocumentsResponse {
  documents: GlobalDocument[];
  totalChunks: number;
}

export interface AdminUploadResponse {
  id: string;
  filename: string;
  size: number;
  status: 'processing';
  message: string;
}

export interface AdminDeleteResponse {
  success: boolean;
  deleted: {
    id: string;
    filename: string;
    chunksRemoved: number;
  };
}

// ============ Error Types ============

export interface ApiError {
  error: string;
  details?: string;
  code?: ErrorCode;
}

export type ErrorCode =
  | 'AUTH_REQUIRED'
  | 'ADMIN_REQUIRED'
  | 'NOT_FOUND'
  | 'VALIDATION_ERROR'
  | 'FILE_TOO_LARGE'
  | 'UPLOAD_LIMIT'
  | 'INVALID_FILE_TYPE'
  | 'SERVICE_ERROR'
  | 'RATE_LIMITED'
  | 'NOT_CONFIGURED';

// ============ Storage Types ============

export interface ThreadMetadata {
  id: string;
  userId: string;
  title: string;
  createdAt: string;
  updatedAt: string;
  uploadCount: number;
}

export interface StoredMessage {
  id: string;
  role: 'user' | 'assistant' | 'tool';
  content: string;
  tool_calls?: ToolCall[];
  tool_call_id?: string;
  name?: string;
  sources?: Source[];
  attachments?: string[];
  generatedDocuments?: GeneratedDocumentInfo[];
  timestamp: string;
}

export interface DocumentRegistry {
  documents: GlobalDocument[];
}

// ============ RAG Types ============

export interface RAGContext {
  query: string;
  globalChunks: RetrievedChunk[];
  userChunks: RetrievedChunk[];
  conversationHistory: Message[];
}

export interface RetrievedChunk {
  id: string;
  text: string;
  documentName: string;
  pageNumber: number;
  score: number;
  source: 'global' | 'user';
}

export interface RAGResponse {
  answer: string;
  sources: Source[];
  generatedDocuments?: GeneratedDocumentInfo[];
  visualizations?: MessageVisualization[];
}

// ============ Session Types ============

export interface SessionUser {
  name?: string | null;
  email?: string | null;
  image?: string | null;
}

export interface Session {
  user?: SessionUser;
  expires: string;
}

// ============ Web Search Types ============

export interface WebSearchResult {
  title: string;
  url: string;
  content: string;
  score?: number;
}

export interface TavilySearchResponse {
  results: WebSearchResult[];
  query: string;
}

// ============ Tavily Settings Types ============

export interface TavilySettings {
  apiKey: string;
  enabled: boolean;
  defaultTopic: 'general' | 'news' | 'finance';
  defaultSearchDepth: 'basic' | 'advanced';
  maxResults: number;
  includeDomains: string[];
  excludeDomains: string[];
  cacheTTLSeconds: number;
  updatedAt: string;
  updatedBy: string;
}
